import { UseLenis } from "@/lib/lenis";
import "./globals.css";
import { giveYouGlory, sans, pacifico } from "@/lib/fonts";
import UseAOS from "@/lib/aos";
import Navigation from "@/components/navigation";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        className={`${sans.variable} ${pacifico.variable} ${giveYouGlory.variable} antialiased font-sans selection:bg-violet-400 selection:text-white`}
      >
        <Navigation />
        <UseLenis />
        <UseAOS />
        {children}
      </body>
    </html>
  );
}
